// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_KIND_UNSPECIFIED     Kind = 0
	Kind_KIND_HELLO           Kind = 1
	Kind_KIND_WELCOME         Kind = 2
	Kind_KIND_STATE           Kind = 3
	Kind_KIND_MOVE            Kind = 4
	Kind_KIND_CHAT            Kind = 5
	Kind_KIND_VOICE_STATE     Kind = 6
	Kind_KIND_REPLY           Kind = 7
	Kind_KIND_MESSAGE         Kind = 8
	Kind_KIND_CLAIM_OWNER     Kind = 9
	Kind_KIND_CREATE_CHANNEL  Kind = 10
	Kind_KIND_UPDATE_CHANNEL  Kind = 11
	Kind_KIND_DELETE_CHANNEL  Kind = 12
	Kind_KIND_WATCH_RESOURCES Kind = 13
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0:  "KIND_UNSPECIFIED",
		1:  "KIND_HELLO",
		2:  "KIND_WELCOME",
		3:  "KIND_STATE",
		4:  "KIND_MOVE",
		5:  "KIND_CHAT",
		6:  "KIND_VOICE_STATE",
		7:  "KIND_REPLY",
		8:  "KIND_MESSAGE",
		9:  "KIND_CLAIM_OWNER",
		10: "KIND_CREATE_CHANNEL",
		11: "KIND_UPDATE_CHANNEL",
		12: "KIND_DELETE_CHANNEL",
		13: "KIND_WATCH_RESOURCES",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":     0,
		"KIND_HELLO":           1,
		"KIND_WELCOME":         2,
		"KIND_STATE":           3,
		"KIND_MOVE":            4,
		"KIND_CHAT":            5,
		"KIND_VOICE_STATE":     6,
		"KIND_REPLY":           7,
		"KIND_MESSAGE":         8,
		"KIND_CLAIM_OWNER":     9,
		"KIND_CREATE_CHANNEL":  10,
		"KIND_UPDATE_CHANNEL":  11,
		"KIND_DELETE_CHANNEL":  12,
		"KIND_WATCH_RESOURCES": 13,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

// Field numbers are permanent. Reserve removed fields instead of reusing them.
// Body is the message selected by Kind, not an additional framed stream.
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Kind                   `protobuf:"varint,1,opt,name=kind,proto3,enum=resona.control.v1.Kind" json:"kind,omitempty"`
	Request       uint32                 `protobuf:"varint,2,opt,name=request,proto3" json:"request,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *Frame) GetRequest() uint32 {
	if x != nil {
		return x.Request
	}
	return 0
}

func (x *Frame) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Hello) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Hello) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Hello) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ClaimOwner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimOwner) Reset() {
	*x = ClaimOwner{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimOwner) ProtoMessage() {}

func (x *ClaimOwner) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimOwner.ProtoReflect.Descriptor instead.
func (*ClaimOwner) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimOwner) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Bitrate       uint32                 `protobuf:"varint,3,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannel) Reset() {
	*x = CreateChannel{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannel) ProtoMessage() {}

func (x *CreateChannel) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannel.ProtoReflect.Descriptor instead.
func (*CreateChannel) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *CreateChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChannel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateChannel) GetBitrate() uint32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

type UpdateChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Bitrate       uint32                 `protobuf:"varint,4,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannel) Reset() {
	*x = UpdateChannel{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannel) ProtoMessage() {}

func (x *UpdateChannel) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannel.ProtoReflect.Descriptor instead.
func (*UpdateChannel) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateChannel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateChannel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateChannel) GetBitrate() uint32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

type DeleteChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannel) Reset() {
	*x = DeleteChannel{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannel) ProtoMessage() {}

func (x *DeleteChannel) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannel.ProtoReflect.Descriptor instead.
func (*DeleteChannel) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteChannel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Atomically replace interest and enqueue its initial snapshot before the reply.
// Current-channel voice state and the caller's permissions are always included.
type WatchResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllChannels   bool                   `protobuf:"varint,1,opt,name=all_channels,json=allChannels,proto3" json:"all_channels,omitempty"`
	AllMembers    bool                   `protobuf:"varint,2,opt,name=all_members,json=allMembers,proto3" json:"all_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResources) Reset() {
	*x = WatchResources{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResources) ProtoMessage() {}

func (x *WatchResources) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResources.ProtoReflect.Descriptor instead.
func (*WatchResources) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *WatchResources) GetAllChannels() bool {
	if x != nil {
		return x.AllChannels
	}
	return false
}

func (x *WatchResources) GetAllMembers() bool {
	if x != nil {
		return x.AllMembers
	}
	return false
}

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Application range: 1..65535.
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Bitrate       uint32                 `protobuf:"varint,4,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *Channel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Channel) GetBitrate() uint32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Channel       uint32                 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Instance      string                 `protobuf:"bytes,4,opt,name=instance,proto3" json:"instance,omitempty"`
	Muted         bool                   `protobuf:"varint,5,opt,name=muted,proto3" json:"muted,omitempty"`
	Deafened      bool                   `protobuf:"varint,6,opt,name=deafened,proto3" json:"deafened,omitempty"`
	Epoch         uint32                 `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *Member) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Member) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *Member) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Member) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *Member) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *Member) GetDeafened() bool {
	if x != nil {
		return x.Deafened
	}
	return false
}

func (x *Member) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type State struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Name                     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Self                     uint32                 `protobuf:"varint,2,opt,name=self,proto3" json:"self,omitempty"`
	Epoch                    uint32                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Channels                 []*Channel             `protobuf:"bytes,4,rep,name=channels,proto3" json:"channels,omitempty"`
	Members                  []*Member              `protobuf:"bytes,5,rep,name=members,proto3" json:"members,omitempty"`
	IdentityUid              string                 `protobuf:"bytes,6,opt,name=identity_uid,json=identityUid,proto3" json:"identity_uid,omitempty"`
	ServerRole               string                 `protobuf:"bytes,7,opt,name=server_role,json=serverRole,proto3" json:"server_role,omitempty"`
	CanClaimOwner            bool                   `protobuf:"varint,8,opt,name=can_claim_owner,json=canClaimOwner,proto3" json:"can_claim_owner,omitempty"`
	CanManageChannels        bool                   `protobuf:"varint,9,opt,name=can_manage_channels,json=canManageChannels,proto3" json:"can_manage_channels,omitempty"`
	CanConfigureChannelAudio bool                   `protobuf:"varint,10,opt,name=can_configure_channel_audio,json=canConfigureChannelAudio,proto3" json:"can_configure_channel_audio,omitempty"`
	CanWatchResources        bool                   `protobuf:"varint,11,opt,name=can_watch_resources,json=canWatchResources,proto3" json:"can_watch_resources,omitempty"`
	Revision                 uint64                 `protobuf:"varint,12,opt,name=revision,proto3" json:"revision,omitempty"`
	AllChannels              bool                   `protobuf:"varint,13,opt,name=all_channels,json=allChannels,proto3" json:"all_channels,omitempty"`
	AllMembers               bool                   `protobuf:"varint,14,opt,name=all_members,json=allMembers,proto3" json:"all_members,omitempty"`
	DefaultChannel           uint32                 `protobuf:"varint,15,opt,name=default_channel,json=defaultChannel,proto3" json:"default_channel,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *State) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *State) GetSelf() uint32 {
	if x != nil {
		return x.Self
	}
	return 0
}

func (x *State) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *State) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *State) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *State) GetIdentityUid() string {
	if x != nil {
		return x.IdentityUid
	}
	return ""
}

func (x *State) GetServerRole() string {
	if x != nil {
		return x.ServerRole
	}
	return ""
}

func (x *State) GetCanClaimOwner() bool {
	if x != nil {
		return x.CanClaimOwner
	}
	return false
}

func (x *State) GetCanManageChannels() bool {
	if x != nil {
		return x.CanManageChannels
	}
	return false
}

func (x *State) GetCanConfigureChannelAudio() bool {
	if x != nil {
		return x.CanConfigureChannelAudio
	}
	return false
}

func (x *State) GetCanWatchResources() bool {
	if x != nil {
		return x.CanWatchResources
	}
	return false
}

func (x *State) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *State) GetAllChannels() bool {
	if x != nil {
		return x.AllChannels
	}
	return false
}

func (x *State) GetAllMembers() bool {
	if x != nil {
		return x.AllMembers
	}
	return false
}

func (x *State) GetDefaultChannel() uint32 {
	if x != nil {
		return x.DefaultChannel
	}
	return 0
}

// VoiceState sets both flags; it is not a partial update. Missing flags mean false.
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Muted         bool                   `protobuf:"varint,3,opt,name=muted,proto3" json:"muted,omitempty"`
	Deafened      bool                   `protobuf:"varint,4,opt,name=deafened,proto3" json:"deafened,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *Command) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *Command) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Command) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *Command) GetDeafened() bool {
	if x != nil {
		return x.Deafened
	}
	return false
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // Application range: 0..255; unknown codes mean failure.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *Reply) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Sender        uint32                 `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *Message) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *Message) GetSender() uint32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Message) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x11resona.control.v1\"b\n" +
	"\x05Frame\x12+\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x17.resona.control.v1.KindR\x04kind\x12\x18\n" +
	"\arequest\x18\x02 \x01(\rR\arequest\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"|\n" +
	"\x05Hello\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\"\n" +
	"\n" +
	"ClaimOwner\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"_\n" +
	"\rCreateChannel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\abitrate\x18\x03 \x01(\rR\abitrate\"o\n" +
	"\rUpdateChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\abitrate\x18\x04 \x01(\rR\abitrate\"\x1f\n" +
	"\rDeleteChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"T\n" +
	"\x0eWatchResources\x12!\n" +
	"\fall_channels\x18\x01 \x01(\bR\vallChannels\x12\x1f\n" +
	"\vall_members\x18\x02 \x01(\bR\n" +
	"allMembers\"i\n" +
	"\aChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\abitrate\x18\x04 \x01(\rR\abitrate\"\xb2\x01\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\achannel\x18\x02 \x01(\rR\achannel\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1a\n" +
	"\binstance\x18\x04 \x01(\tR\binstance\x12\x14\n" +
	"\x05muted\x18\x05 \x01(\bR\x05muted\x12\x1a\n" +
	"\bdeafened\x18\x06 \x01(\bR\bdeafened\x12\x14\n" +
	"\x05epoch\x18\a \x01(\rR\x05epoch\"\xc6\x04\n" +
	"\x05State\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04self\x18\x02 \x01(\rR\x04self\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\rR\x05epoch\x126\n" +
	"\bchannels\x18\x04 \x03(\v2\x1a.resona.control.v1.ChannelR\bchannels\x123\n" +
	"\amembers\x18\x05 \x03(\v2\x19.resona.control.v1.MemberR\amembers\x12!\n" +
	"\fidentity_uid\x18\x06 \x01(\tR\videntityUid\x12\x1f\n" +
	"\vserver_role\x18\a \x01(\tR\n" +
	"serverRole\x12&\n" +
	"\x0fcan_claim_owner\x18\b \x01(\bR\rcanClaimOwner\x12.\n" +
	"\x13can_manage_channels\x18\t \x01(\bR\x11canManageChannels\x12=\n" +
	"\x1bcan_configure_channel_audio\x18\n" +
	" \x01(\bR\x18canConfigureChannelAudio\x12.\n" +
	"\x13can_watch_resources\x18\v \x01(\bR\x11canWatchResources\x12\x1a\n" +
	"\brevision\x18\f \x01(\x04R\brevision\x12!\n" +
	"\fall_channels\x18\r \x01(\bR\vallChannels\x12\x1f\n" +
	"\vall_members\x18\x0e \x01(\bR\n" +
	"allMembers\x12'\n" +
	"\x0fdefault_channel\x18\x0f \x01(\rR\x0edefaultChannel\"i\n" +
	"\aCommand\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05muted\x18\x03 \x01(\bR\x05muted\x12\x1a\n" +
	"\bdeafened\x18\x04 \x01(\bR\bdeafened\"\x1b\n" +
	"\x05Reply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\"k\n" +
	"\aMessage\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\rR\x06sender\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text*\x9f\x02\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"KIND_HELLO\x10\x01\x12\x10\n" +
	"\fKIND_WELCOME\x10\x02\x12\x0e\n" +
	"\n" +
	"KIND_STATE\x10\x03\x12\r\n" +
	"\tKIND_MOVE\x10\x04\x12\r\n" +
	"\tKIND_CHAT\x10\x05\x12\x14\n" +
	"\x10KIND_VOICE_STATE\x10\x06\x12\x0e\n" +
	"\n" +
	"KIND_REPLY\x10\a\x12\x10\n" +
	"\fKIND_MESSAGE\x10\b\x12\x14\n" +
	"\x10KIND_CLAIM_OWNER\x10\t\x12\x17\n" +
	"\x13KIND_CREATE_CHANNEL\x10\n" +
	"\x12\x17\n" +
	"\x13KIND_UPDATE_CHANNEL\x10\v\x12\x17\n" +
	"\x13KIND_DELETE_CHANNEL\x10\f\x12\x18\n" +
	"\x14KIND_WATCH_RESOURCES\x10\rB3Z1github.com/tsukiyoz/resona/internal/nativewire/pbb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_control_proto_goTypes = []any{
	(Kind)(0),              // 0: resona.control.v1.Kind
	(*Frame)(nil),          // 1: resona.control.v1.Frame
	(*Hello)(nil),          // 2: resona.control.v1.Hello
	(*ClaimOwner)(nil),     // 3: resona.control.v1.ClaimOwner
	(*CreateChannel)(nil),  // 4: resona.control.v1.CreateChannel
	(*UpdateChannel)(nil),  // 5: resona.control.v1.UpdateChannel
	(*DeleteChannel)(nil),  // 6: resona.control.v1.DeleteChannel
	(*WatchResources)(nil), // 7: resona.control.v1.WatchResources
	(*Channel)(nil),        // 8: resona.control.v1.Channel
	(*Member)(nil),         // 9: resona.control.v1.Member
	(*State)(nil),          // 10: resona.control.v1.State
	(*Command)(nil),        // 11: resona.control.v1.Command
	(*Reply)(nil),          // 12: resona.control.v1.Reply
	(*Message)(nil),        // 13: resona.control.v1.Message
}
var file_control_proto_depIdxs = []int32{
	0, // 0: resona.control.v1.Frame.kind:type_name -> resona.control.v1.Kind
	8, // 1: resona.control.v1.State.channels:type_name -> resona.control.v1.Channel
	9, // 2: resona.control.v1.State.members:type_name -> resona.control.v1.Member
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		EnumInfos:         file_control_proto_enumTypes,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
