// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_KIND_UNSPECIFIED Kind = 0
	Kind_KIND_HELLO       Kind = 1
	Kind_KIND_WELCOME     Kind = 2
	Kind_KIND_STATE       Kind = 3
	Kind_KIND_MOVE        Kind = 4
	Kind_KIND_CHAT        Kind = 5
	Kind_KIND_VOICE_STATE Kind = 6
	Kind_KIND_REPLY       Kind = 7
	Kind_KIND_MESSAGE     Kind = 8
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_HELLO",
		2: "KIND_WELCOME",
		3: "KIND_STATE",
		4: "KIND_MOVE",
		5: "KIND_CHAT",
		6: "KIND_VOICE_STATE",
		7: "KIND_REPLY",
		8: "KIND_MESSAGE",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_HELLO":       1,
		"KIND_WELCOME":     2,
		"KIND_STATE":       3,
		"KIND_MOVE":        4,
		"KIND_CHAT":        5,
		"KIND_VOICE_STATE": 6,
		"KIND_REPLY":       7,
		"KIND_MESSAGE":     8,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

// Field numbers are permanent. Reserve removed fields instead of reusing them.
// Body is the message selected by Kind, not an additional framed stream.
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Kind                   `protobuf:"varint,1,opt,name=kind,proto3,enum=resona.control.v1.Kind" json:"kind,omitempty"`
	Request       uint32                 `protobuf:"varint,2,opt,name=request,proto3" json:"request,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *Frame) GetRequest() uint32 {
	if x != nil {
		return x.Request
	}
	return 0
}

func (x *Frame) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Hello) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Application range: 1..65535.
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *Channel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Channel       uint32                 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Instance      string                 `protobuf:"bytes,4,opt,name=instance,proto3" json:"instance,omitempty"`
	Muted         bool                   `protobuf:"varint,5,opt,name=muted,proto3" json:"muted,omitempty"`
	Deafened      bool                   `protobuf:"varint,6,opt,name=deafened,proto3" json:"deafened,omitempty"`
	Epoch         uint32                 `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *Member) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Member) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *Member) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Member) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *Member) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *Member) GetDeafened() bool {
	if x != nil {
		return x.Deafened
	}
	return false
}

func (x *Member) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Self          uint32                 `protobuf:"varint,2,opt,name=self,proto3" json:"self,omitempty"`
	Epoch         uint32                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Channels      []*Channel             `protobuf:"bytes,4,rep,name=channels,proto3" json:"channels,omitempty"`
	Members       []*Member              `protobuf:"bytes,5,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *State) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *State) GetSelf() uint32 {
	if x != nil {
		return x.Self
	}
	return 0
}

func (x *State) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *State) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *State) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

// VoiceState sets both flags; it is not a partial update. Missing flags mean false.
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Muted         bool                   `protobuf:"varint,3,opt,name=muted,proto3" json:"muted,omitempty"`
	Deafened      bool                   `protobuf:"varint,4,opt,name=deafened,proto3" json:"deafened,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *Command) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Command) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *Command) GetDeafened() bool {
	if x != nil {
		return x.Deafened
	}
	return false
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // Application range: 0..255; unknown codes mean failure.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *Reply) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       uint32                 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Sender        uint32                 `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *Message) GetSender() uint32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Message) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x11resona.control.v1\"b\n" +
	"\x05Frame\x12+\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x17.resona.control.v1.KindR\x04kind\x12\x18\n" +
	"\arequest\x18\x02 \x01(\rR\arequest\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"?\n" +
	"\x05Hello\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"O\n" +
	"\aChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xb2\x01\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\achannel\x18\x02 \x01(\rR\achannel\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1a\n" +
	"\binstance\x18\x04 \x01(\tR\binstance\x12\x14\n" +
	"\x05muted\x18\x05 \x01(\bR\x05muted\x12\x1a\n" +
	"\bdeafened\x18\x06 \x01(\bR\bdeafened\x12\x14\n" +
	"\x05epoch\x18\a \x01(\rR\x05epoch\"\xb2\x01\n" +
	"\x05State\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04self\x18\x02 \x01(\rR\x04self\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\rR\x05epoch\x126\n" +
	"\bchannels\x18\x04 \x03(\v2\x1a.resona.control.v1.ChannelR\bchannels\x123\n" +
	"\amembers\x18\x05 \x03(\v2\x19.resona.control.v1.MemberR\amembers\"i\n" +
	"\aCommand\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05muted\x18\x03 \x01(\bR\x05muted\x12\x1a\n" +
	"\bdeafened\x18\x04 \x01(\bR\bdeafened\"\x1b\n" +
	"\x05Reply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\"k\n" +
	"\aMessage\x12\x18\n" +
	"\achannel\x18\x01 \x01(\rR\achannel\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\rR\x06sender\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text*\xa4\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"KIND_HELLO\x10\x01\x12\x10\n" +
	"\fKIND_WELCOME\x10\x02\x12\x0e\n" +
	"\n" +
	"KIND_STATE\x10\x03\x12\r\n" +
	"\tKIND_MOVE\x10\x04\x12\r\n" +
	"\tKIND_CHAT\x10\x05\x12\x14\n" +
	"\x10KIND_VOICE_STATE\x10\x06\x12\x0e\n" +
	"\n" +
	"KIND_REPLY\x10\a\x12\x10\n" +
	"\fKIND_MESSAGE\x10\bB3Z1github.com/tsukiyoz/resona/internal/nativewire/pbb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_control_proto_goTypes = []any{
	(Kind)(0),       // 0: resona.control.v1.Kind
	(*Frame)(nil),   // 1: resona.control.v1.Frame
	(*Hello)(nil),   // 2: resona.control.v1.Hello
	(*Channel)(nil), // 3: resona.control.v1.Channel
	(*Member)(nil),  // 4: resona.control.v1.Member
	(*State)(nil),   // 5: resona.control.v1.State
	(*Command)(nil), // 6: resona.control.v1.Command
	(*Reply)(nil),   // 7: resona.control.v1.Reply
	(*Message)(nil), // 8: resona.control.v1.Message
}
var file_control_proto_depIdxs = []int32{
	0, // 0: resona.control.v1.Frame.kind:type_name -> resona.control.v1.Kind
	3, // 1: resona.control.v1.State.channels:type_name -> resona.control.v1.Channel
	4, // 2: resona.control.v1.State.members:type_name -> resona.control.v1.Member
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		EnumInfos:         file_control_proto_enumTypes,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
